/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTaiLieu.view;

import QLTaiLieu.service.DocService_dthkhanh;
import QLTaiLieu.service.JournalService_dthkhanh;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlytailieu.Journal_dthkhanh;

/**
 *
 * @author DELL
 */
public class JournalFrame_dthkhanh extends javax.swing.JFrame {

    JournalService_dthkhanh journalService;
    DefaultTableModel defaultTableModel;
    Journal_dthkhanh journal;

    public JournalFrame_dthkhanh() throws SQLException {
        initComponents();
        journalService = new JournalService_dthkhanh();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        journalTable.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã tài liệu");
        defaultTableModel.addColumn("Tên nhà xuất bản");
        defaultTableModel.addColumn("Số bản phát hành");
        defaultTableModel.addColumn("Số phát hành");
        defaultTableModel.addColumn("Tháng phát hành");

        setTableData(journalService.getAllUsers());

    }
   private void setTableData(List<Journal_dthkhanh> journals) {
        for (Journal_dthkhanh journal : journals) {
            defaultTableModel.addRow(new Object[]{journal.getMaTaiLieu(), journal.getTenNhaXuatBan(), journal.getSoBanPhatHanh(), journal.getSoPhatHanh(),
                journal.getThangPhatHanh()});

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tenNXBTextField = new javax.swing.JTextField();
        soBanPHTextField = new javax.swing.JTextField();
        soPhatHanhTextField = new javax.swing.JTextField();
        addJournalButton = new javax.swing.JButton();
        deleteJournaButton = new javax.swing.JButton();
        backJournalButton = new javax.swing.JButton();
        findJournalTextField = new javax.swing.JTextField();
        findJournalButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        journalTable = new javax.swing.JTable();
        thangPHComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ TẠP CHÍ");
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 17));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhà xuất bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số bản phát hành");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số phát hành");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tháng phát hành");

        addJournalButton.setText("Thêm");
        addJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJournalButtonActionPerformed(evt);
            }
        });

        deleteJournaButton.setText("Xóa");
        deleteJournaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJournaButtonActionPerformed(evt);
            }
        });

        backJournalButton.setText("Quay lại");
        backJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJournalButtonActionPerformed(evt);
            }
        });

        findJournalButton.setText("Tìm kiếm");
        findJournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findJournalButtonActionPerformed(evt);
            }
        });

        journalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(journalTable);

        thangPHComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findJournalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(deleteJournaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(backJournalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thangPHComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tenNXBTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(soBanPHTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(soPhatHanhTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenNXBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(soBanPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soPhatHanhTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(thangPHComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addJournalButton)
                            .addComponent(deleteJournaButton)
                            .addComponent(backJournalButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findJournalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findJournalButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJournalButtonActionPerformed
        // TODO add your handling code here:
        
        
           journal.setTenNhaXuatBan(tenNXBTextField.getText());
        journal.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
        journal.setSoPhatHanh(Integer.parseInt(soPhatHanhTextField.getText()));
        journal.setThangPhatHanh(String.valueOf(thangPHComboBox.getSelectedItem()));
        
        try {
            journalService.addJournal(journal);
        } catch (SQLException ex) {
            Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_addJournalButtonActionPerformed

    private void deleteJournaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJournaButtonActionPerformed
         // TODO add your handling code here:
        int row = journalTable.getSelectedRow();
        if (row == -1)//nguoi dung chua chon hang nao
        {
            JOptionPane.showMessageDialog(JournalFrame_dthkhanh.this, "Vui lòng chọn tạp chí cần xóa trước", "loi", JOptionPane.ERROR_MESSAGE);

        } else {
            int confirm = JOptionPane.showConfirmDialog(JournalFrame_dthkhanh.this, "Bạn chắc chắn muốn xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {

                try {
                    int userId = Integer.valueOf(String.valueOf(journalTable.getValueAt(row, 0)));

                    journalService.deleteJournal(userId);

                    defaultTableModel.setRowCount(0);//de xoa het du lieu hien tai
                    setTableData(journalService.getAllUsers());
                } catch (SQLException ex) {
                    Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_deleteJournaButtonActionPerformed

    private void backJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJournalButtonActionPerformed
        // TODO add your handling code here:
        new DocumentFrame_dthkhanh().setVisible(true);
        this.dispose();//de an form hien tai
    }//GEN-LAST:event_backJournalButtonActionPerformed

    private void findJournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findJournalButtonActionPerformed
        // TODO add your handling code here:
         int row = journalTable.getSelectedRow();
        if (row == -1)//nguoi dung chua chon hang nao
        {
            JOptionPane.showMessageDialog(JournalFrame_dthkhanh.this, "Vui lòng nhập giá trị cần tìm", "Lỗi", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_findJournalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JournalFrame_dthkhanh().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJournalButton;
    private javax.swing.JButton backJournalButton;
    private javax.swing.JButton deleteJournaButton;
    private javax.swing.JButton findJournalButton;
    private javax.swing.JTextField findJournalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable journalTable;
    private javax.swing.JTextField soBanPHTextField;
    private javax.swing.JTextField soPhatHanhTextField;
    private javax.swing.JTextField tenNXBTextField;
    private javax.swing.JComboBox<String> thangPHComboBox;
    // End of variables declaration//GEN-END:variables
}
