/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTaiLieu.view;

import QLTaiLieu.service.NewpaperService_dthkhanh;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlytailieu.Newpaper_dthkhanh;
/**
 *
 * @author DELL
 */
public class NewpaperFrame_dthkhanh extends javax.swing.JFrame {
NewpaperService_dthkhanh newpaperService;
    DefaultTableModel defaultTableModel;
Newpaper_dthkhanh newpaper;
    public NewpaperFrame_dthkhanh() throws SQLException {
        initComponents();
        newpaperService = new NewpaperService_dthkhanh();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        newppTable.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã tài liệu");
        defaultTableModel.addColumn("Tên nhà xuất bản");
        defaultTableModel.addColumn("Số bản phát hành");
        defaultTableModel.addColumn("Ngày phát hành");

        setTableData(newpaperService.getAllUsers());

    }
   private void setTableData(List<Newpaper_dthkhanh> books) {
        for (Newpaper_dthkhanh book : books) {
            defaultTableModel.addRow(new Object[]{book.getMaTaiLieu(), book.getTenNhaXuatBan(), book.getSoBanPhatHanh(), book.getNgayPhatHanh()});

        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tenNXBTextField = new javax.swing.JTextField();
        soBanPHTextField = new javax.swing.JTextField();
        addnewppButton = new javax.swing.JButton();
        deletenewppButton = new javax.swing.JButton();
        backnewppButton = new javax.swing.JButton();
        findnewppTextField = new javax.swing.JTextField();
        findnewppButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newppTable = new javax.swing.JTable();
        ngayPHTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ BÁO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhà xuất bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số bản phát hành");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày phát hành");

        tenNXBTextField.setPreferredSize(new java.awt.Dimension(175, 20));

        soBanPHTextField.setPreferredSize(new java.awt.Dimension(175, 20));

        addnewppButton.setText("Thêm");
        addnewppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewppButtonActionPerformed(evt);
            }
        });

        deletenewppButton.setText("Xóa");
        deletenewppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletenewppButtonActionPerformed(evt);
            }
        });

        backnewppButton.setText("Quay lại");
        backnewppButton.setToolTipText("");
        backnewppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backnewppButtonActionPerformed(evt);
            }
        });

        findnewppButton.setText("Tìm kiếm");
        findnewppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findnewppButtonActionPerformed(evt);
            }
        });

        newppTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(newppTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(findnewppButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addnewppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(deletenewppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(backnewppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(findnewppTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tenNXBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(soBanPHTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ngayPHTextField))))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tenNXBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soBanPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ngayPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addnewppButton)
                            .addComponent(deletenewppButton)
                            .addComponent(backnewppButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findnewppTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findnewppButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backnewppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backnewppButtonActionPerformed
        // TODO add your handling code here:
        new DocumentFrame_dthkhanh().setVisible(true);
        this.dispose();//de an form hien tai
    }//GEN-LAST:event_backnewppButtonActionPerformed

    private void findnewppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findnewppButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_findnewppButtonActionPerformed

    private void deletenewppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletenewppButtonActionPerformed
        // TODO add your handling code here:
        int row = newppTable.getSelectedRow();
        if (row == -1)//nguoi dung chua chon hang nao
        {
            JOptionPane.showMessageDialog(NewpaperFrame_dthkhanh.this, "Vui lòng chọn tạp chí cần xóa trước", "loi", JOptionPane.ERROR_MESSAGE);

        } else {
            int confirm = JOptionPane.showConfirmDialog(NewpaperFrame_dthkhanh.this, "Bạn chắc chắn muốn xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {

                try {
                    int userId = Integer.valueOf(String.valueOf(newppTable.getValueAt(row, 0)));

                    newpaperService.deleteNewpaper(userId);

                    defaultTableModel.setRowCount(0);//de xoa het du lieu hien tai
                    setTableData(newpaperService.getAllUsers());
                } catch (SQLException ex) {
                    Logger.getLogger(NewpaperFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_deletenewppButtonActionPerformed

    private void addnewppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewppButtonActionPerformed
        // TODO add your handling code here:
         newpaper.setTenNhaXuatBan(tenNXBTextField.getText());
        newpaper.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
        newpaper.setNgayPhatHanh(Integer.parseInt(ngayPHTextField.getText()));
        
        try {
            newpaperService.addNewpaper(newpaper);
        } catch (SQLException ex) {
            Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            new JournalFrame_dthkhanh().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JournalFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addnewppButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewpaperFrame_dthkhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    //</editor-fold>
    
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new NewpaperFrame_dthkhanh().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(NewpaperFrame_dthkhanh.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewppButton;
    private javax.swing.JButton backnewppButton;
    private javax.swing.JButton deletenewppButton;
    private javax.swing.JButton findnewppButton;
    private javax.swing.JTextField findnewppTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable newppTable;
    private javax.swing.JTextField ngayPHTextField;
    private javax.swing.JTextField soBanPHTextField;
    private javax.swing.JTextField tenNXBTextField;
    // End of variables declaration//GEN-END:variables
}
